#!/usr/bin/env node
if (Number(process.versions.node.split('.')[0]) < 10) {
  console.error('copher requires Node.js 10 or higher');
  process.exit(1);
}

// We need this to squash the warning about Symbol.asyncIterator
const { join } = require('path');
const { spawn } = require('child_process');
spawn(
  'node',
  ['--no-warnings', join(__dirname, 'index.js'), ...process.argv.slice(2)],
  { stdio: 'inherit' }
);
