#!/usr/bin/env node
if (Number(process.versions.node.split('.')[0]) < 10) {
  console.error('copher requires Node.js 10 or higher');
  process.exit(1);
}

// We need this to squash the warning about Symbol.asyncIterator
const path = require('path');
const index = path.join(__dirname, 'index.js');
require('child_process').spawn('node', ['--no-warnings', index, ...process.argv.slice(2)]);
